services:
  redis-docker:
    hostname: redis
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379

  app:
    build: .
    env_file:
      - .env
    container_name: 'swyp-app'
    restart: always
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis-docker
      REDIS_PORT: 6379
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    networks:
      - app-network
    depends_on:
      - redis-docker

networks:
  app-network:
    driver: bridge
