spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER:local}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: 604800 # 7일 (7 * 24 * 60 * 60)
  refresh-token-validity-in-seconds: 5184000 # 60일 (60 * 24 * 60 * 60)

logging:
  level:
    com.swyp: DEBUG
    org.springframework:
      web: DEBUG
      security: DEBUG
      security.oauth2: DEBUG 