spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: futsal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 580000    
      idle-timeout: 300000    
      connection-timeout: 30000  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: 604800 # 7일 (7 * 24 * 60 * 60)
  refresh-token-validity-in-seconds: 5184000 # 60일 (60 * 24 * 60 * 60)

firebase:
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH}

server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: None
        secure: true

cloud:
  aws:
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: ${NCP_BUCKET}

logging:
  level:
    com.swyp: DEBUG
    org.springframework:
      web: DEBUG
      security: DEBUG
      security.oauth2: DEBUG 